import { BoardDefinition, TileType, Direction } from '../types';

export const MAELSTROM_BOARD: BoardDefinition = {
    id: 'maelstrom',
    name: 'Maelstrom',
    width: 12,
    height: 12,

    startingPositions: [
    ],

    tiles: [
        { position: { x: 0, y: 11 }, type: TileType.REPAIR },
        { position: { x: 8, y: 11 }, type: TileType.OPTION },
        { position: { x: 3, y: 0 }, type: TileType.OPTION },
        { position: { x: 11, y: 0 }, type: TileType.REPAIR },
        { position: { x: 0, y: 10 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.RIGHT },
        { position: { x: 1, y: 9 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.UP },
        { position: { x: 1, y: 8 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.UP },
        { position: { x: 1, y: 7 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.UP },
        { position: { x: 1, y: 6 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.UP },
        { position: { x: 1, y: 5 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.UP },
        { position: { x: 1, y: 4 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.UP },
        { position: { x: 1, y: 3 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.UP },
        { position: { x: 1, y: 2 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.UP },
        { position: { x: 1, y: 0 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.DOWN },
        { position: { x: 2, y: 1 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.RIGHT },
        { position: { x: 4, y: 1 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.RIGHT },
        { position: { x: 5, y: 1 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.RIGHT },
        { position: { x: 6, y: 1 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.RIGHT },
        { position: { x: 7, y: 1 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.RIGHT },
        { position: { x: 3, y: 1 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.RIGHT },
        { position: { x: 8, y: 1 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.RIGHT },
        { position: { x: 5, y: 0 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.DOWN },
        { position: { x: 11, y: 1 }, type: TileType.CONVEYOR, direction: Direction.LEFT },
        { position: { x: 10, y: 2 }, type: TileType.CONVEYOR, direction: Direction.DOWN },
        { position: { x: 10, y: 3 }, type: TileType.CONVEYOR, direction: Direction.DOWN },
        { position: { x: 10, y: 4 }, type: TileType.CONVEYOR, direction: Direction.DOWN },
        { position: { x: 10, y: 5 }, type: TileType.CONVEYOR, direction: Direction.DOWN },
        { position: { x: 10, y: 6 }, type: TileType.CONVEYOR, direction: Direction.DOWN },
        { position: { x: 10, y: 7 }, type: TileType.CONVEYOR, direction: Direction.DOWN },
        { position: { x: 10, y: 8 }, type: TileType.CONVEYOR, direction: Direction.DOWN },
        { position: { x: 10, y: 11 }, type: TileType.CONVEYOR, direction: Direction.UP },
        { position: { x: 9, y: 10 }, type: TileType.CONVEYOR, direction: Direction.LEFT },
        { position: { x: 8, y: 10 }, type: TileType.CONVEYOR, direction: Direction.LEFT },
        { position: { x: 7, y: 10 }, type: TileType.CONVEYOR, direction: Direction.LEFT },
        { position: { x: 6, y: 10 }, type: TileType.CONVEYOR, direction: Direction.LEFT },
        { position: { x: 5, y: 10 }, type: TileType.CONVEYOR, direction: Direction.LEFT },
        { position: { x: 4, y: 10 }, type: TileType.CONVEYOR, direction: Direction.LEFT },
        { position: { x: 3, y: 10 }, type: TileType.CONVEYOR, direction: Direction.LEFT },
        { position: { x: 2, y: 9 }, type: TileType.CONVEYOR, direction: Direction.UP },
        { position: { x: 2, y: 8 }, type: TileType.CONVEYOR, direction: Direction.UP },
        { position: { x: 2, y: 7 }, type: TileType.CONVEYOR, direction: Direction.UP },
        { position: { x: 2, y: 6 }, type: TileType.CONVEYOR, direction: Direction.UP },
        { position: { x: 2, y: 5 }, type: TileType.CONVEYOR, direction: Direction.UP },
        { position: { x: 2, y: 4 }, type: TileType.CONVEYOR, direction: Direction.UP },
        { position: { x: 2, y: 3 }, type: TileType.CONVEYOR, direction: Direction.UP },
        { position: { x: 3, y: 2 }, type: TileType.CONVEYOR, direction: Direction.RIGHT },
        { position: { x: 4, y: 2 }, type: TileType.CONVEYOR, direction: Direction.RIGHT },
        { position: { x: 5, y: 2 }, type: TileType.CONVEYOR, direction: Direction.RIGHT },
        { position: { x: 6, y: 2 }, type: TileType.CONVEYOR, direction: Direction.RIGHT },
        { position: { x: 7, y: 2 }, type: TileType.CONVEYOR, direction: Direction.RIGHT },
        { position: { x: 8, y: 2 }, type: TileType.CONVEYOR, direction: Direction.RIGHT },
        { position: { x: 8, y: 3 }, type: TileType.CONVEYOR, direction: Direction.DOWN },
        { position: { x: 8, y: 4 }, type: TileType.CONVEYOR, direction: Direction.DOWN },
        { position: { x: 8, y: 5 }, type: TileType.CONVEYOR, direction: Direction.DOWN },
        { position: { x: 8, y: 6 }, type: TileType.CONVEYOR, direction: Direction.DOWN },
        { position: { x: 8, y: 7 }, type: TileType.CONVEYOR, direction: Direction.DOWN },
        { position: { x: 9, y: 2 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.DOWN },
        { position: { x: 9, y: 3 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.DOWN },
        { position: { x: 9, y: 4 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.DOWN },
        { position: { x: 9, y: 5 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.DOWN },
        { position: { x: 9, y: 6 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.DOWN },
        { position: { x: 9, y: 7 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.DOWN },
        { position: { x: 9, y: 8 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.DOWN },
        { position: { x: 8, y: 9 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.LEFT },
        { position: { x: 7, y: 9 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.LEFT },
        { position: { x: 6, y: 9 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.LEFT },
        { position: { x: 5, y: 9 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.LEFT },
        { position: { x: 4, y: 9 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.LEFT },
        { position: { x: 3, y: 8 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.UP },
        { position: { x: 3, y: 7 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.UP },
        { position: { x: 3, y: 6 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.UP },
        { position: { x: 3, y: 5 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.UP },
        { position: { x: 3, y: 4 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.UP },
        { position: { x: 4, y: 3 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.RIGHT },
        { position: { x: 5, y: 3 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.RIGHT },
        { position: { x: 6, y: 3 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.RIGHT },
        { position: { x: 7, y: 3 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.RIGHT },
        { position: { x: 7, y: 4 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.DOWN },
        { position: { x: 7, y: 5 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.DOWN },
        { position: { x: 7, y: 6 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.DOWN },
        { position: { x: 5, y: 4 }, type: TileType.CONVEYOR, direction: Direction.RIGHT },
        { position: { x: 4, y: 4 }, type: TileType.CONVEYOR, direction: Direction.RIGHT, rotate: 'clockwise' },
        { position: { x: 4, y: 5 }, type: TileType.CONVEYOR, direction: Direction.UP },
        { position: { x: 4, y: 6 }, type: TileType.CONVEYOR, direction: Direction.UP },
        { position: { x: 4, y: 7 }, type: TileType.CONVEYOR, direction: Direction.UP },
        { position: { x: 5, y: 8 }, type: TileType.CONVEYOR, direction: Direction.LEFT },
        { position: { x: 6, y: 8 }, type: TileType.CONVEYOR, direction: Direction.LEFT },
        { position: { x: 7, y: 8 }, type: TileType.CONVEYOR, direction: Direction.LEFT },
        { position: { x: 5, y: 5 }, type: TileType.PIT },
        { position: { x: 5, y: 6 }, type: TileType.PIT },
        { position: { x: 6, y: 6 }, type: TileType.PIT },
        { position: { x: 6, y: 5 }, type: TileType.PIT },
        { position: { x: 5, y: 7 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.UP, rotate: 'clockwise' },
        { position: { x: 7, y: 7 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.LEFT, rotate: 'clockwise' },
        { position: { x: 6, y: 7 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.LEFT },
        { position: { x: 3, y: 3 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.RIGHT, rotate: 'clockwise' },
        { position: { x: 3, y: 9 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.UP, rotate: 'clockwise' },
        { position: { x: 9, y: 9 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.LEFT, rotate: 'clockwise' },
        { position: { x: 9, y: 1 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.DOWN, rotate: 'clockwise' },
        { position: { x: 1, y: 1 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.RIGHT, rotate: 'clockwise' },
        { position: { x: 1, y: 10 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.UP, rotate: 'counterclockwise' },
        { position: { x: 0, y: 6 }, type: TileType.EXPRESS_CONVEYOR, direction: Direction.RIGHT },
        { position: { x: 0, y: 9 }, type: TileType.PUSHER, direction: Direction.RIGHT, registers: [2, 4] },
        { position: { x: 0, y: 7 }, type: TileType.PUSHER, direction: Direction.RIGHT, registers: [1, 3, 5] },
        { position: { x: 0, y: 4 }, type: TileType.PUSHER, direction: Direction.RIGHT, registers: [1, 3, 5] },
        { position: { x: 0, y: 2 }, type: TileType.PUSHER, direction: Direction.RIGHT, registers: [2, 4] },
        { position: { x: 2, y: 0 }, type: TileType.PUSHER, direction: Direction.DOWN, registers: [2, 4] },
        { position: { x: 4, y: 0 }, type: TileType.PUSHER, direction: Direction.DOWN, registers: [1, 3, 5] },
        { position: { x: 2, y: 11 }, type: TileType.PUSHER, direction: Direction.UP, registers: [2, 4] },
        { position: { x: 9, y: 11 }, type: TileType.PUSHER, direction: Direction.UP, registers: [2, 4] },
        { position: { x: 7, y: 11 }, type: TileType.PUSHER, direction: Direction.UP, registers: [1, 3, 5] },
        { position: { x: 4, y: 11 }, type: TileType.PUSHER, direction: Direction.UP, registers: [1, 3, 5] },
        { position: { x: 11, y: 7 }, type: TileType.PUSHER, direction: Direction.LEFT, registers: [1, 3, 5] },
        { position: { x: 11, y: 4 }, type: TileType.PUSHER, direction: Direction.LEFT, registers: [1, 3, 5] },
        { position: { x: 11, y: 9 }, type: TileType.PUSHER, direction: Direction.LEFT, registers: [2, 4] },
        { position: { x: 11, y: 2 }, type: TileType.PUSHER, direction: Direction.LEFT, registers: [2, 4] },
        { position: { x: 9, y: 0 }, type: TileType.PUSHER, direction: Direction.DOWN, registers: [2, 4] },
        { position: { x: 7, y: 0 }, type: TileType.PUSHER, direction: Direction.DOWN, registers: [1, 3, 5] },
        { position: { x: 10, y: 1 }, type: TileType.CONVEYOR, direction: Direction.DOWN, rotate: 'counterclockwise' },
        { position: { x: 10, y: 9 }, type: TileType.CONVEYOR, direction: Direction.DOWN },
        { position: { x: 2, y: 10 }, type: TileType.CONVEYOR, direction: Direction.UP, rotate: 'clockwise' },
        { position: { x: 2, y: 2 }, type: TileType.CONVEYOR, direction: Direction.RIGHT, rotate: 'clockwise' },
        { position: { x: 6, y: 0 }, type: TileType.CONVEYOR, direction: Direction.UP },
        { position: { x: 6, y: 11 }, type: TileType.CONVEYOR, direction: Direction.UP },
        { position: { x: 11, y: 6 }, type: TileType.CONVEYOR, direction: Direction.RIGHT },
        { position: { x: 11, y: 5 }, type: TileType.CONVEYOR, direction: Direction.LEFT },
        { position: { x: 6, y: 4 }, type: TileType.CONVEYOR, direction: Direction.DOWN, rotate: 'clockwise' },
    ],

    lasers: [
        { position: { x: 3, y: 6 }, direction: Direction.RIGHT, damage: 1 },
        { position: { x: 4, y: 5 }, direction: Direction.RIGHT, damage: 1 },
        { position: { x: 5, y: 3 }, direction: Direction.DOWN, damage: 1 },
        { position: { x: 6, y: 4 }, direction: Direction.DOWN, damage: 1 },
    ],

    walls: [
        { position: { x: 0, y: 7 }, sides: [Direction.LEFT] },
        { position: { x: 0, y: 9 }, sides: [Direction.LEFT] },
        { position: { x: 0, y: 4 }, sides: [Direction.LEFT] },
        { position: { x: 0, y: 2 }, sides: [Direction.LEFT] },
        { position: { x: 2, y: 0 }, sides: [Direction.UP] },
        { position: { x: 4, y: 0 }, sides: [Direction.UP] },
        { position: { x: 7, y: 0 }, sides: [Direction.UP] },
        { position: { x: 9, y: 0 }, sides: [Direction.UP] },
        { position: { x: 11, y: 2 }, sides: [Direction.RIGHT] },
        { position: { x: 11, y: 4 }, sides: [Direction.RIGHT] },
        { position: { x: 11, y: 7 }, sides: [Direction.RIGHT] },
        { position: { x: 11, y: 9 }, sides: [Direction.RIGHT] },
        { position: { x: 5, y: 7 }, sides: [Direction.DOWN] },
        { position: { x: 6, y: 8 }, sides: [Direction.DOWN] },
        { position: { x: 6, y: 4 }, sides: [Direction.UP] },
        { position: { x: 4, y: 5 }, sides: [Direction.LEFT] },
        { position: { x: 3, y: 6 }, sides: [Direction.LEFT] },
        { position: { x: 7, y: 6 }, sides: [Direction.RIGHT] },
        { position: { x: 8, y: 5 }, sides: [Direction.RIGHT] },
        { position: { x: 5, y: 3 }, sides: [Direction.UP] },
        { position: { x: 9, y: 11 }, sides: [Direction.DOWN] },
        { position: { x: 7, y: 11 }, sides: [Direction.DOWN] },
        { position: { x: 4, y: 11 }, sides: [Direction.DOWN] },
        { position: { x: 2, y: 11 }, sides: [Direction.DOWN] },
    ],
};